export const ALL_TODO_FAILURE = "ALL_TODO_FAILURE";
export const ALL_TODO_STARTED = "ALL_TODO_STARTED";
export const ALL_TODO_SUCCESS = "ALL_TODO_SUCCESS";

export const PAGES_TODO_SUCCESS = "PAGES_TODO_SUCCESS";

export const ALL_AUTHOR_SUCCESS = "ALL_AUTHOR_SUCCESS";
export const ALL_LOCATION_SUCCESS = "ALL_LOCATION_SUCCESS";
